# Generated by Django 5.2.3 on 2025-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('quizscore', models.IntegerField()),
                ('tictactoescore', models.IntegerField()),
                ('stonescore', models.IntegerField()),
                ('snakescore', models.IntegerField()),
            ],
        ),
    ]
